// Code generated by jsonschema. DO NOT EDIT.
package beerjson

// ID: https://raw.githubusercontent.com/beerjson/beerjson/master/json/equipment.json

// The descriptive base type for brew day equipment. Provides unique properties to fully describe the recipe.
type EquipmentBase struct {
	KeyType           *string           `json:"type,omitempty"`
	EquipmentBaseForm EquipmentBaseForm `json:"form", validate:"required"`
	MaximumVolume     VolumeType        `json:"maximum_volume", validate:"required"`
	Name              string            `json:"name", validate:"required"`
}

type EquipmentBaseForm string

const (
	EquipmentBaseForm_HLT             EquipmentBaseForm = "HLT"
	EquipmentBaseForm_MashTun         EquipmentBaseForm = "Mash Tun"
	EquipmentBaseForm_LauterTun       EquipmentBaseForm = "Lauter Tun"
	EquipmentBaseForm_BrewKettle      EquipmentBaseForm = "Brew Kettle"
	EquipmentBaseForm_Fermenter       EquipmentBaseForm = "Fermenter"
	EquipmentBaseForm_AgingVessel     EquipmentBaseForm = "Aging Vessel"
	EquipmentBaseForm_PackagingVessel EquipmentBaseForm = "Packaging Vessel"
)

// EquipmentType provides necessary information for individual brewing equipment.
type EquipmentItemType struct {
	Notes *string `json:"notes,omitempty"`
	// The volume boiled off during 1 hour, measured before and after at room temperature.
	BoilRatePerHour   *VolumeType        `json:"boil_rate_per_hour,omitempty"`
	KeyType           *string            `json:"type,omitempty"`
	EquipmentBaseForm *EquipmentBaseForm `json:"form,omitempty"`
	// The volume that leaves the kettle, especially important for non-immersion chillers that cool the wort as it leaves the kettle.
	DrainRatePerMinute *VolumeType `json:"drain_rate_per_minute,omitempty"`
	// The specific heat of the piece of equipment, expressed in Cal/(g*C), especially important for when the mashtun is not preheated.
	SpecificHeat *SpecificHeatType `json:"specific_heat,omitempty"`
	// The apparent volume absorbed by grain, typical values are 0.125 qt/lb (1.04 L/kg) for a mashtun, 0.08 gal/lb (0.66 L/kg) for BIAB.
	GrainAbsorptionRate *SpecificVolumeType `json:"grain_absorption_rate,omitempty"`
	Name                *string             `json:"name,omitempty"`
	MaximumVolume       *VolumeType         `json:"maximum_volume,omitempty"`
	// The weight of the piece of equipment, especially important for when the mashtun is not preheated.
	Weight *MassType  `json:"weight,omitempty"`
	Loss   VolumeType `json:"loss", validate:"required"`
}

// Provides necessary information for brewing equipment set.
type EquipmentType struct {
	Name           string              `json:"name", validate:"required"`
	EquipmentItems []EquipmentItemType `json:"equipment_items", validate:"required"`
}
