// Code generated by jsonschema. DO NOT EDIT.
package beerjson

// ID: https://raw.githubusercontent.com/beerjson/beerjson/master/json/fermentation.json

// FermentationProcedureType defines the procedure for performing fermentation.
type FermentationProcedureType struct {
	FermentationSteps []FermentationStepType `json:"fermentation_steps", validate:"required"`
	Name              string                 `json:"name", validate:"required"`
	Description       *string                `json:"description,omitempty"`
	Notes             *string                `json:"notes,omitempty"`
}
