// Code generated by jsonschema. DO NOT EDIT.
package beerjson

import "encoding/json"
import "fmt"

// ID: https://raw.githubusercontent.com/beerjson/beerjson/master/json/mash_step.json

// MashStepType - a per step representation occurring during the mash.
type MashStepType struct {
	Name             string           `json:"name", validate:"required"`
	MashStepTypeType MashStepTypeType `json:"type", validate:"required"`
	StepTemperature  TemperatureType  `json:"step_temperature", validate:"required"`
	// The amount of time  that passes before this step begins. eg moving from a mash step (step 1) of 148F, to a new temperature step of 156F (step 2) may take 8 minutes to heat the mash. Step 2 would have a ramp time of 8 minutes.
	RampTime *TimeType `json:"ramp_time,omitempty"`
	// Also known as the mash thickness. eg 1.75 qt/lb or 3.65 L/kg.
	WaterGrainRatio *SpecificVolumeType `json:"water_grain_ratio,omitempty"`
	EndPH           *AcidityType        `json:"end_pH,omitempty"`
	Amount          *VolumeType         `json:"amount,omitempty"`
	StepTime        TimeType            `json:"step_time", validate:"required"`
	EndTemperature  *TemperatureType    `json:"end_temperature,omitempty"`
	Description     *string             `json:"description,omitempty"`
	// Temperature of the water for an infusion step.
	InfuseTemperature *TemperatureType `json:"infuse_temperature,omitempty"`
	StartPH           *AcidityType     `json:"start_pH,omitempty"`
}

type MashStepTypeType string

func (s *MashStepTypeType) UnmarshalJSON(b []byte) error {
	var v string
	err := json.Unmarshal(b, &v)
	if err != nil {
		return err
	}

	*s = MashStepTypeType(v)

	switch *s {
	case MashStepTypeType_Infusion:
		return nil
	case MashStepTypeType_Temperature:
		return nil
	case MashStepTypeType_Decoction:
		return nil
	case MashStepTypeType_SouringMash:
		return nil
	case MashStepTypeType_SouringWort:
		return nil
	case MashStepTypeType_DrainMashTun:
		return nil
	case MashStepTypeType_Sparge:
		return nil
	}
	return fmt.Errorf("MashStepTypeType: value '%v' does not match any value", v)
}

const (
	MashStepTypeType_Infusion     MashStepTypeType = "infusion"
	MashStepTypeType_Temperature  MashStepTypeType = "temperature"
	MashStepTypeType_Decoction    MashStepTypeType = "decoction"
	MashStepTypeType_SouringMash  MashStepTypeType = "souring mash"
	MashStepTypeType_SouringWort  MashStepTypeType = "souring wort"
	MashStepTypeType_DrainMashTun MashStepTypeType = "drain mash tun"
	MashStepTypeType_Sparge       MashStepTypeType = "sparge"
)
