// Code generated by jsonschema. DO NOT EDIT.
package beerjson

// ID: https://raw.githubusercontent.com/beerjson/beerjson/master/json/packaging.json

// Describes the procedure for packaging your beverage.
type PackagingProcedureType struct {
	Name             string                `json:"name", validate:"required"`
	PackagedVolume   *VolumeType           `json:"packaged_volume,omitempty"`
	Description      *string               `json:"description,omitempty"`
	Notes            *string               `json:"notes,omitempty"`
	PackagingVessels []PackagingVesselType `json:"packaging_vessels,omitempty"`
}
