// Code generated by jsonschema. DO NOT EDIT.
package beerjson

import "encoding/json"
import "fmt"

// ID: https://raw.githubusercontent.com/beerjson/beerjson/master/json/packaging_vessel.json

// PackagingVesselType - a per vessel representation of a packaging process.
type PackagingVesselType struct {
	PackageDate             *DateType                `json:"package_date,omitempty"`
	EndPh                   *AcidityType             `json:"end_ph,omitempty"`
	EndTemperature          *TemperatureType         `json:"end_temperature,omitempty"`
	EndGravity              *GravityType             `json:"end_gravity,omitempty"`
	VesselQuantity          *float64                 `json:"vessel_quantity,omitempty"`
	Name                    string                   `json:"name", validate:"required"`
	PackagingVesselTypeType *PackagingVesselTypeType `json:"type,omitempty"`
	StepTime                *TimeType                `json:"step_time,omitempty"`
	StartGravity            *GravityType             `json:"start_gravity,omitempty"`
	StartPh                 *AcidityType             `json:"start_ph,omitempty"`
	Description             *string                  `json:"description,omitempty"`
	StartTemperature        *TemperatureType         `json:"start_temperature,omitempty"`
	Carbonation             *float64                 `json:"carbonation,omitempty"`
	VesselVolume            *VolumeType              `json:"vessel_volume,omitempty"`
}

type PackagingVesselTypeType string

func (s *PackagingVesselTypeType) UnmarshalJSON(b []byte) error {
	var v string
	err := json.Unmarshal(b, &v)
	if err != nil {
		return err
	}

	*s = PackagingVesselTypeType(v)

	switch *s {
	case PackagingVesselTypeType_Keg:
		return nil
	case PackagingVesselTypeType_Bottle:
		return nil
	case PackagingVesselTypeType_Cask:
		return nil
	case PackagingVesselTypeType_Tank:
		return nil
	case PackagingVesselTypeType_Firkin:
		return nil
	case PackagingVesselTypeType_Other:
		return nil
	}
	return fmt.Errorf("PackagingVesselTypeType: value '%v' does not match any value", v)
}

const (
	PackagingVesselTypeType_Keg    PackagingVesselTypeType = "keg"
	PackagingVesselTypeType_Bottle PackagingVesselTypeType = "bottle"
	PackagingVesselTypeType_Cask   PackagingVesselTypeType = "cask"
	PackagingVesselTypeType_Tank   PackagingVesselTypeType = "tank"
	PackagingVesselTypeType_Firkin PackagingVesselTypeType = "firkin"
	PackagingVesselTypeType_Other  PackagingVesselTypeType = "other"
)
