// Code generated by jsonschema. DO NOT EDIT.
package beerjson

// ID: https://raw.githubusercontent.com/beerjson/beerjson/master/json/packaging_vessel.json

// PackagingVesselType - a per vessel representation of a packaging process.
type PackagingVesselType struct {
	StartTemperature        *TemperatureType         `json:"start_temperature,omitempty"`
	EndPh                   *AcidityType             `json:"end_ph,omitempty"`
	VesselVolume            *VolumeType              `json:"vessel_volume,omitempty"`
	PackagingVesselTypeType *PackagingVesselTypeType `json:"type,omitempty"`
	Description             *string                  `json:"description,omitempty"`
	EndGravity              *GravityType             `json:"end_gravity,omitempty"`
	Name                    string                   `json:"name", validate:"required"`
	StepTime                *TimeType                `json:"step_time,omitempty"`
	StartPh                 *AcidityType             `json:"start_ph,omitempty"`
	VesselQuantity          *float64                 `json:"vessel_quantity,omitempty"`
	PackageDate             *DateType                `json:"package_date,omitempty"`
	EndTemperature          *TemperatureType         `json:"end_temperature,omitempty"`
	StartGravity            *GravityType             `json:"start_gravity,omitempty"`
	Carbonation             *float64                 `json:"carbonation,omitempty"`
}

type PackagingVesselTypeType string

const (
	PackagingVesselTypeType_Keg    PackagingVesselTypeType = "keg"
	PackagingVesselTypeType_Bottle PackagingVesselTypeType = "bottle"
	PackagingVesselTypeType_Cask   PackagingVesselTypeType = "cask"
	PackagingVesselTypeType_Tank   PackagingVesselTypeType = "tank"
	PackagingVesselTypeType_Firkin PackagingVesselTypeType = "firkin"
	PackagingVesselTypeType_Other  PackagingVesselTypeType = "other"
)
