// Code generated by jsonschema. DO NOT EDIT.
package beerjson

// ID: https://raw.githubusercontent.com/beerjson/beerjson/master/json/style.json

// RecipeStyleType defines style information stored in a recipe record
type RecipeStyleType struct {
	StyleBase *StyleBase `json:"StyleBase,omitempty"`
}

// The descriptive base type for both style guideline records, and recipe style provisions. Provides unique properties to identify individual styles
type StyleBase struct {
	Name           string          `json:"name", validate:"required"`
	Category       string          `json:"category", validate:"required"`
	CategoryNumber *int32          `json:"category_number,omitempty"`
	StyleLetter    *string         `json:"style_letter,omitempty", validate:"max=1,min=1,regex=[A-Z ]"`
	StyleGuide     string          `json:"style_guide", validate:"required"`
	KeyType        StyleCategories `json:"type", validate:"required"`
}

type StyleCategories string

const (
	StyleCategories_Beer     StyleCategories = "beer"
	StyleCategories_Cider    StyleCategories = "cider"
	StyleCategories_Kombucha StyleCategories = "kombucha"
	StyleCategories_Mead     StyleCategories = "mead"
	StyleCategories_Other    StyleCategories = "other"
	StyleCategories_Soda     StyleCategories = "soda"
	StyleCategories_Wine     StyleCategories = "wine"
)

// StyleType provide information for Style categorization
type StyleType struct {
	Aroma                        *string               `json:"aroma,omitempty"`
	Flavor                       *string               `json:"flavor,omitempty"`
	OverallImpression            *string               `json:"overall_impression,omitempty"`
	Examples                     *string               `json:"examples,omitempty"`
	OriginalGravity              *GravityRangeType     `json:"original_gravity,omitempty"`
	Carbonation                  *CarbonationRangeType `json:"carbonation,omitempty"`
	FinalGravity                 *GravityRangeType     `json:"final_gravity,omitempty"`
	Color                        *ColorRangeType       `json:"color,omitempty"`
	InternationalBitternessUnits *BitternessRangeType  `json:"international_bitterness_units,omitempty"`
	Ingredients                  *string               `json:"ingredients,omitempty"`
	AlcoholByVolume              *PercentRangeType     `json:"alcohol_by_volume,omitempty"`
	Notes                        *string               `json:"notes,omitempty"`
	StyleBase                    *StyleBase            `json:"StyleBase,omitempty"`
	Appearance                   *string               `json:"appearance,omitempty"`
	Mouthfeel                    *string               `json:"mouthfeel,omitempty"`
}
