// Code generated by jsonschema. DO NOT EDIT.
package beerjson

import "encoding/json"
import "fmt"

// ID: https://raw.githubusercontent.com/beerjson/beerjson/master/json/style.json

// RecipeStyleType defines style information stored in a recipe record
type RecipeStyleType struct {
	StyleGuide     *string          `json:"style_guide,omitempty"`
	KeyType        *StyleCategories `json:"type,omitempty"`
	Name           *string          `json:"name,omitempty"`
	Category       *string          `json:"category,omitempty"`
	CategoryNumber *int32           `json:"category_number,omitempty"`
	StyleLetter    *string          `json:"style_letter,omitempty", validate:"max=1,min=1,regex=[A-Z ]"`
}

// The descriptive base type for both style guideline records, and recipe style provisions. Provides unique properties to identify individual styles
type StyleBase struct {
	StyleGuide     string          `json:"style_guide", validate:"required"`
	KeyType        StyleCategories `json:"type", validate:"required"`
	Name           string          `json:"name", validate:"required"`
	Category       string          `json:"category", validate:"required"`
	CategoryNumber *int32          `json:"category_number,omitempty"`
	StyleLetter    *string         `json:"style_letter,omitempty", validate:"max=1,min=1,regex=[A-Z ]"`
}

type StyleCategories string

func (s *StyleCategories) UnmarshalJSON(b []byte) error {
	var v string
	err := json.Unmarshal(b, &v)
	if err != nil {
		return err
	}

	*s = StyleCategories(v)

	switch *s {
	case StyleCategories_Beer:
		return nil
	case StyleCategories_Cider:
		return nil
	case StyleCategories_Kombucha:
		return nil
	case StyleCategories_Mead:
		return nil
	case StyleCategories_Other:
		return nil
	case StyleCategories_Soda:
		return nil
	case StyleCategories_Wine:
		return nil
	}
	return fmt.Errorf("StyleCategories: value '%v' does not match any value", v)
}

const (
	StyleCategories_Beer     StyleCategories = "beer"
	StyleCategories_Cider    StyleCategories = "cider"
	StyleCategories_Kombucha StyleCategories = "kombucha"
	StyleCategories_Mead     StyleCategories = "mead"
	StyleCategories_Other    StyleCategories = "other"
	StyleCategories_Soda     StyleCategories = "soda"
	StyleCategories_Wine     StyleCategories = "wine"
)

// StyleType provide information for Style categorization
type StyleType struct {
	Examples                     *string               `json:"examples,omitempty"`
	KeyType                      *StyleCategories      `json:"type,omitempty"`
	Name                         *string               `json:"name,omitempty"`
	OriginalGravity              *GravityRangeType     `json:"original_gravity,omitempty"`
	Carbonation                  *CarbonationRangeType `json:"carbonation,omitempty"`
	Flavor                       *string               `json:"flavor,omitempty"`
	FinalGravity                 *GravityRangeType     `json:"final_gravity,omitempty"`
	Category                     *string               `json:"category,omitempty"`
	Color                        *ColorRangeType       `json:"color,omitempty"`
	OverallImpression            *string               `json:"overall_impression,omitempty"`
	Appearance                   *string               `json:"appearance,omitempty"`
	Ingredients                  *string               `json:"ingredients,omitempty"`
	Aroma                        *string               `json:"aroma,omitempty"`
	Mouthfeel                    *string               `json:"mouthfeel,omitempty"`
	InternationalBitternessUnits *BitternessRangeType  `json:"international_bitterness_units,omitempty"`
	StyleLetter                  *string               `json:"style_letter,omitempty", validate:"min=1,regex=[A-Z ],max=1"`
	StyleGuide                   *string               `json:"style_guide,omitempty"`
	CategoryNumber               *int32                `json:"category_number,omitempty"`
	Notes                        *string               `json:"notes,omitempty"`
	AlcoholByVolume              *PercentRangeType     `json:"alcohol_by_volume,omitempty"`
}
